services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - crispr
    depends_on:
      - backend
  admin:
    build: ./admin
    ports:
      - "5174:5173"
    networks:
      - crispr
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    networks:
      - crispr
    env_file:
      - ./backend/.env

networks:
  crispr:
    driver: bridge